// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCSvAF9rJW7qkudduOIV2a7zs0LTjSuajA',
    appId: '1:491534265378:web:a91cae28917b15193aae7b',
    messagingSenderId: '491534265378',
    projectId: 'flutterfirebase-1befb',
    authDomain: 'flutterfirebase-1befb.firebaseapp.com',
    storageBucket: 'flutterfirebase-1befb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD74FzSKIkTTH5lWVESKqmpIjz-SiNJsXM',
    appId: '1:491534265378:android:92a6375f353945ba3aae7b',
    messagingSenderId: '491534265378',
    projectId: 'flutterfirebase-1befb',
    storageBucket: 'flutterfirebase-1befb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjeOH_hKN86fNUnaODE9PM1AY5HO9MiN0',
    appId: '1:491534265378:ios:684cf89c3f33bcd83aae7b',
    messagingSenderId: '491534265378',
    projectId: 'flutterfirebase-1befb',
    storageBucket: 'flutterfirebase-1befb.appspot.com',
    iosBundleId: 'com.example.firebaseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjeOH_hKN86fNUnaODE9PM1AY5HO9MiN0',
    appId: '1:491534265378:ios:c59ea6b6042532053aae7b',
    messagingSenderId: '491534265378',
    projectId: 'flutterfirebase-1befb',
    storageBucket: 'flutterfirebase-1befb.appspot.com',
    iosBundleId: 'com.example.firebaseProject.RunnerTests',
  );
}
